const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate')

const Survey = mongoose.model('surveys');

module.exports = app => {
    app.post('/api/surveys', requireLogin/*making sure the user is logged in*/, requireCredits/*making sure the user has credits*/, async (req, res) => {
        try {
            const { title, subject, body, recipients } = req.body;

            const survey = new Survey({
                title, //ES6 syntax because the key and value are identical
                subject,
                body,
                recipient: recipients.split(',')/*remove commas and return an array of strings*/.map((email) => ({ email: email.trim() }))/*returns an array of objects*/,
                _user: req.user.id, //the current user's id, generated by mongoDB
                dateSent: Date.now()
            });

            const mailer = new Mailer(survey, surveyTemplate(survey));
            await mailer.send();
        } catch (error) {
            console.log(error);
            console.log(error.response.body)
        }
    });
};